#!/bin/sh

. /etc/rc.subr

name="awning"
rcvar=awning_enable

command_interpreter=/usr/local/bin/node
command="/usr/sbin/awning/intro.js"

start_cmd="/usr/sbin/daemon -u pierre ${command}"
load_rc_config $name
run_rc_command "$1"
